# Copyright (c) 2024 MDSANIMA DEV. All rights reserved.
# Licensed under the MIT license.

# This is a configuration file for the `Oh My Zsh` terminal and Powerlevel10k
# Zsh theme. Check the https://github.com/romkatv/powerlevel10k/ for more info.

# We have removed all unused commands and help comments from this configuration
# file. Type in the terminal `p10k configure` to generate new config.


# Generated by Powerlevel10k configuration wizard and customized by mdsanima.
# Based on romkatv/powerlevel10k/config/p10k-lean.zsh, checksum 26839.
# Wizard options: nerdfont-v3 + powerline, small icons, unicode, lean, 24h time,
# 1 line, compact, many icons, fluent, instant_prompt=verbose.
# Config for Powerlevel10k with lean prompt style.
#
# Here's a one-liner to print colormap:
# for i in {0..255}; do print -Pn "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%6)):#3}:+$'\n'}; done

# Temporarily change options.
'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
    emulate -L zsh -o extended_glob
    unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'

    # Zsh >= 5.1 is required.
    [[ $ZSH_VERSION == (5.<1->*|<6->.*) ]] || return

    ##############################[ left segment ]##############################
    typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
        context                 # user@hostname
        dir                     # current directory
        vcs                     # git status
        prompt_char             # prompt symbol
    )

    #############################[ right segment ]##############################
    typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
        status                  # exit code of the last command
        command_execution_time  # duration of the last command
        background_jobs         # presence of background jobs
        virtualenv              # python virtual environment
        package                 # name@version from package.json
        node_version            # node.js version
        kubecontext             # current kubernetes context
        gcloud                  # google cloud cli account and project
        time                    # current time
    )

    # Defines character set used by powerlevel10k.
    typeset -g POWERLEVEL9K_MODE=nerdfont-v3

    # When set to `none`, spaces are not added.
    typeset -g POWERLEVEL9K_ICON_PADDING=none

    # Basic style options that define the overall look of your prompt.
    typeset -g POWERLEVEL9K_BACKGROUND=                            # transparent background
    typeset -g POWERLEVEL9K_{LEFT,RIGHT}_{LEFT,RIGHT}_WHITESPACE=  # no surrounding whitespace
    typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SUBSEGMENT_SEPARATOR=' '  # separate segments with a space
    typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SEGMENT_SEPARATOR=        # no end-of-line symbol

    # When set to true, icons appear before content on both sides of the prompt.
    typeset -g POWERLEVEL9K_ICON_BEFORE_CONTENT=true

    # Add an empty line before each prompt.
    typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=false

    # Connect left prompt lines with these symbols.
    typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=
    typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX=
    typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=

    # Connect right prompt lines with these symbols.
    typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_SUFFIX=
    typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_SUFFIX=
    typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_SUFFIX=

    # The left end of left prompt.
    typeset -g POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=

    # The right end of right prompt.
    typeset -g POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL=

    # Filler between left and right prompt on the first prompt line.
    typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR=' '
    if [[ $POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR != ' ' ]]; then
        # The color of the filler.
        typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_FOREGROUND=242
        # Add a space between the end of left prompt and the filler.
        typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=' '
        # Add a space between the filler and the start of right prompt.
        typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL=' '
        # Start filler from the edge of the screen if there are no left segments on the first line.
        typeset -g POWERLEVEL9K_EMPTY_LINE_LEFT_PROMPT_FIRST_SEGMENT_END_SYMBOL='%{%}'
        # End filler on the edge of the screen if there are no right segments on the first line.
        typeset -g POWERLEVEL9K_EMPTY_LINE_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='%{%}'
    fi

    #########################[ context: user@hostname ]#########################
    typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=1
    typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_FOREGROUND=45
    typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND=45
    typeset -g POWERLEVEL9K_CONTEXT_ROOT_TEMPLATE='%n'
    typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_TEMPLATE='%n'
    typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE='%n'

    #########################[ dir: current directory ]#########################
    typeset -g POWERLEVEL9K_DIR_FOREGROUND=27
    typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
    typeset -g POWERLEVEL9K_SHORTEN_DELIMITER=
    typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=25
    typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=37
    typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true
    local anchor_files=(
        .bzr
        .citc
        .git
        .hg
        .node-version
        .python-version
        .go-version
        .ruby-version
        .lua-version
        .java-version
        .perl-version
        .php-version
        .tool-version
        .shorten_folder_marker
        .svn
        .terraform
        CVS
        Cargo.toml
        composer.json
        go.mod
        package.json
        stack.yaml
    )
    typeset -g POWERLEVEL9K_SHORTEN_FOLDER_MARKER="(${(j:|:)anchor_files})"
    typeset -g POWERLEVEL9K_DIR_TRUNCATE_BEFORE_MARKER=false
    typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
    typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=120
    typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS=50
    typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS_PCT=60
    typeset -g POWERLEVEL9K_DIR_HYPERLINK=false
    typeset -g POWERLEVEL9K_DIR_SHOW_WRITABLE=v3
    typeset -g POWERLEVEL9K_LOCK_ICON='🔒'
    typeset -g POWERLEVEL9K_DIR_PREFIX='%fin '

    # Custom icons and colors for different directories.
    typeset -g POWERLEVEL9K_DIR_CLASSES=(
        '~/workspace(|/*)'  WORKSPACE  ''
        '~(|/*)'            HOME       ''
        '*'                 DEFAULT    ''
    )

    # Styling for WORKSPACE.
    typeset -g POWERLEVEL9K_DIR_WORKSPACE_VISUAL_IDENTIFIER_EXPANSION='💼'
    typeset -g POWERLEVEL9K_DIR_WORKSPACE_FOREGROUND=50
    typeset -g POWERLEVEL9K_DIR_WORKSPACE_SHORTENED_FOREGROUND=44
    typeset -g POWERLEVEL9K_DIR_WORKSPACE_ANCHOR_FOREGROUND=39

    # Styling for WORKSPACE_NOT_WRITABLE.
    typeset -g POWERLEVEL9K_DIR_WORKSPACE_NOT_WRITABLE_VISUAL_IDENTIFIER_EXPANSION='🧰'
    typeset -g POWERLEVEL9K_DIR_WORKSPACE_NOT_WRITABLE_FOREGROUND=202
    typeset -g POWERLEVEL9K_DIR_WORKSPACE_NOT_WRITABLE_SHORTENED_FOREGROUND=214
    typeset -g POWERLEVEL9K_DIR_WORKSPACE_NOT_WRITABLE_ANCHOR_FOREGROUND=208

    # Styling for WORKSPACE_NON_EXISTENT.
    typeset -g POWERLEVEL9K_DIR_WORKSPACE_NON_EXISTENT_VISUAL_IDENTIFIER_EXPANSION='🚧'
    typeset -g POWERLEVEL9K_DIR_WORKSPACE_NON_EXISTENT_FOREGROUND=196
    typeset -g POWERLEVEL9K_DIR_WORKSPACE_NON_EXISTENT_SHORTENED_FOREGROUND=208
    typeset -g POWERLEVEL9K_DIR_WORKSPACE_NON_EXISTENT_ANCHOR_FOREGROUND=202

    # Styling for HOME.
    typeset -g POWERLEVEL9K_DIR_HOME_VISUAL_IDENTIFIER_EXPANSION='🤿'
    typeset -g POWERLEVEL9K_DIR_HOME_FOREGROUND=42
    typeset -g POWERLEVEL9K_DIR_HOME_SHORTENED_FOREGROUND=36
    typeset -g POWERLEVEL9K_DIR_HOME_ANCHOR_FOREGROUND=31

    ############################[ vcs: git status ]#############################
    typeset -g POWERLEVEL9K_VCS_BRANCH_ICON='\uF126 '
    typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON='?'

    # Formatter for Git status.
    function mdsanima_git_formatter() {
        emulate -L zsh

        if [[ -n $P9K_CONTENT ]]; then
            typeset -g mdsanima_git_format=$P9K_CONTENT
            return
        fi

        if (( $1 )); then
            # Styling for up-to-date Git status.
            local       meta='%f'     # default foreground
            local      clean='%30F'   # green foreground
            local     staged='%202F'  # orange foreground
            local   modified='%220F'  # yellow foreground
            local  untracked='%39F'   # blue foreground
            local conflicted='%196F'  # red foreground
        else
            # Styling for incomplete and stale Git status.
            local       meta='%244F'  # grey foreground
            local      clean='%244F'  # grey foreground
            local     staged='%244F'  # grey foreground
            local   modified='%244F'  # grey foreground
            local  untracked='%244F'  # grey foreground
            local conflicted='%244F'  # grey foreground
        fi

        local res

        if [[ -n $VCS_STATUS_LOCAL_BRANCH ]]; then
            local branch=${(V)VCS_STATUS_LOCAL_BRANCH}
            # If local branch name is at most 32 characters long, show it in full.
            # Otherwise show the first 12 … the last 12.
            # Tip: To always show local branch name in full without truncation, delete the next line.
            (( $#branch > 32 )) && branch[13,-13]="…"  # <-- this line
            res+="${clean}${(g::)POWERLEVEL9K_VCS_BRANCH_ICON}${branch//\%/%%}"
        fi

        if [[ -n $VCS_STATUS_TAG
              # Show tag only if not on a branch.
              # Tip: To always show tag, delete the next line.
              && -z $VCS_STATUS_LOCAL_BRANCH  # <-- this line
            ]]; then
            local tag=${(V)VCS_STATUS_TAG}
            # If tag name is at most 32 characters long, show it in full.
            # Otherwise show the first 12 … the last 12.
            # Tip: To always show tag name in full without truncation, delete the next line.
            (( $#tag > 32 )) && tag[13,-13]="…"  # <-- this line
            res+="${meta}#${clean}${tag//\%/%%}"
        fi

        # Display the current Git commit if there is no branch and no tag.
        # Tip: To always display the current Git commit, delete the next line.
        [[ -z $VCS_STATUS_LOCAL_BRANCH && -z $VCS_STATUS_TAG ]] &&  # <-- this line
            res+="${meta}@${clean}${VCS_STATUS_COMMIT[1,8]}"

        # Show tracking branch name if it differs from local branch.
        if [[ -n ${VCS_STATUS_REMOTE_BRANCH:#$VCS_STATUS_LOCAL_BRANCH} ]]; then
            res+="${meta}:${clean}${(V)VCS_STATUS_REMOTE_BRANCH//\%/%%}"
        fi

        # Display "wip" if the latest commit's summary contains "wip" or "WIP".
        if [[ $VCS_STATUS_COMMIT_SUMMARY == (|*[^[:alnum:]])(wip|WIP)(|[^[:alnum:]]*) ]]; then
            res+=" ${modified}wip"
        fi

        if (( VCS_STATUS_COMMITS_AHEAD || VCS_STATUS_COMMITS_BEHIND )); then
            # ⇣42 if behind the remote.
            (( VCS_STATUS_COMMITS_BEHIND )) && res+=" ${clean}⇣${VCS_STATUS_COMMITS_BEHIND}"
            # ⇡42 if ahead of the remote; no leading space if also behind the remote: ⇣42⇡42.
            (( VCS_STATUS_COMMITS_AHEAD && !VCS_STATUS_COMMITS_BEHIND )) && res+=" "
            (( VCS_STATUS_COMMITS_AHEAD  )) && res+="${clean}⇡${VCS_STATUS_COMMITS_AHEAD}"
        elif [[ -n $VCS_STATUS_REMOTE_BRANCH ]]; then
            # Tip: Uncomment the next line to display '=' if up to date with the remote.
            # res+=" ${clean}="
        fi

        # ⇠42 if behind the push remote.
        (( VCS_STATUS_PUSH_COMMITS_BEHIND )) && res+=" ${clean}⇠${VCS_STATUS_PUSH_COMMITS_BEHIND}"
        (( VCS_STATUS_PUSH_COMMITS_AHEAD && !VCS_STATUS_PUSH_COMMITS_BEHIND )) && res+=" "
        # ⇢42 if ahead of the push remote; no leading space if also behind: ⇠42⇢42.
        (( VCS_STATUS_PUSH_COMMITS_AHEAD  )) && res+="${clean}⇢${VCS_STATUS_PUSH_COMMITS_AHEAD}"
        # *42 if have stashes.
        (( VCS_STATUS_STASHES        )) && res+=" ${clean}*${VCS_STATUS_STASHES}"
        # 'merge' if the repo is in an unusual state.
        [[ -n $VCS_STATUS_ACTION     ]] && res+=" ${conflicted}${VCS_STATUS_ACTION}"
        # ~42 if have merge conflicts.
        (( VCS_STATUS_NUM_CONFLICTED )) && res+=" ${conflicted}~${VCS_STATUS_NUM_CONFLICTED}"
        # +42 if have staged changes.
        (( VCS_STATUS_NUM_STAGED     )) && res+=" ${staged}+${VCS_STATUS_NUM_STAGED}"
        # !42 if have unstaged changes.
        (( VCS_STATUS_NUM_UNSTAGED   )) && res+=" ${modified}!${VCS_STATUS_NUM_UNSTAGED}"
        # ?42 if have untracked files. It's really a question mark, your font isn't broken.
        # See POWERLEVEL9K_VCS_UNTRACKED_ICON above if you want to use a different icon.
        # Remove the next line if you don't want to see untracked files at all.
        (( VCS_STATUS_NUM_UNTRACKED  )) && res+=" ${untracked}${(g::)POWERLEVEL9K_VCS_UNTRACKED_ICON}${VCS_STATUS_NUM_UNTRACKED}"
        # "─" if the number of unstaged files is unknown. This can happen due to
        # POWERLEVEL9K_VCS_MAX_INDEX_SIZE_DIRTY (see below) being set to a non-negative number lower
        # than the number of files in the Git index, or due to bash.showDirtyState being set to false
        # in the repository config. The number of staged and untracked files may also be unknown
        # in this case.
        (( VCS_STATUS_HAS_UNSTAGED == -1 )) && res+=" ${modified}─"

        typeset -g mdsanima_git_format=$res
    }
    functions -M mdsanima_git_formatter 2>/dev/null

    # Negative value means infinity.
    typeset -g POWERLEVEL9K_VCS_MAX_INDEX_SIZE_DIRTY=-1

    # Don't show Git status in prompt for repositories whose workdir matches this pattern.
    typeset -g POWERLEVEL9K_VCS_DISABLED_WORKDIR_PATTERN='~'

    # Disable the default Git status formatting.
    typeset -g POWERLEVEL9K_VCS_DISABLE_GITSTATUS_FORMATTING=true
    # Install our own Git status formatter.
    typeset -g POWERLEVEL9K_VCS_CONTENT_EXPANSION='${$((mdsanima_git_formatter(1)))+${mdsanima_git_format}}'
    typeset -g POWERLEVEL9K_VCS_LOADING_CONTENT_EXPANSION='${$((mdsanima_git_formatter(0)))+${mdsanima_git_format}}'
    # Enable counters for staged, unstaged, etc.
    typeset -g POWERLEVEL9K_VCS_{STAGED,UNSTAGED,UNTRACKED,CONFLICTED,COMMITS_AHEAD,COMMITS_BEHIND}_MAX_NUM=-1

    # Icon color.
    typeset -g POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_COLOR=8
    typeset -g POWERLEVEL9K_VCS_LOADING_VISUAL_IDENTIFIER_COLOR=208

    # Custom prefix.
    typeset -g POWERLEVEL9K_VCS_PREFIX='%fon '

    # Show status of repositories of these types.
    typeset -g POWERLEVEL9K_VCS_BACKENDS=(git)

    # These settings are used for repo other than Git or when gitstatusd fails.
    typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=8
    typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=39
    typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=220

    #######################[ prompt_char: prompt symbol ]#######################
    typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=7
    typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=196
    typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='❯'
    typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_CONTENT_EXPANSION='❮'
    typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIVIS_CONTENT_EXPANSION='V'
    typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIOWR_CONTENT_EXPANSION='▶'
    typeset -g POWERLEVEL9K_PROMPT_CHAR_OVERWRITE_STATE=true
    typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=''
    typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=

    #################[ status: exit code of the last command ]##################
    typeset -g POWERLEVEL9K_STATUS_EXTENDED_STATES=true
    typeset -g POWERLEVEL9K_STATUS_OK=false
    typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=106
    typeset -g POWERLEVEL9K_STATUS_OK_VISUAL_IDENTIFIER_EXPANSION='✔'
    typeset -g POWERLEVEL9K_STATUS_OK_PIPE=true
    typeset -g POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND=106
    typeset -g POWERLEVEL9K_STATUS_OK_PIPE_VISUAL_IDENTIFIER_EXPANSION='✔'
    typeset -g POWERLEVEL9K_STATUS_ERROR=true
    typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=196
    typeset -g POWERLEVEL9K_STATUS_ERROR_VISUAL_IDENTIFIER_EXPANSION='✘'
    typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL=true
    typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND=196
    typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_VISUAL_IDENTIFIER_EXPANSION='✘'
    typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE=true
    typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND=196
    typeset -g POWERLEVEL9K_STATUS_VERBOSE_SIGNAME=false
    typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_VISUAL_IDENTIFIER_EXPANSION='✘'

    ##########[ command_execution_time: duration of the last command ]##########
    typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=1
    typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=3
    typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=220
    typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='d h m s'

    ##############[ background_jobs: presence of background jobs ]##############
    typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=false
    typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=243
    typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VISUAL_IDENTIFIER_EXPANSION='🔧'

    #################[ virtualenv: python virtual environment ]#################
    typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND=35
    typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=true
    typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_WITH_PYENV=true
    typeset -g POWERLEVEL9K_VIRTUALENV_{LEFT,RIGHT}_DELIMITER=

    ################[ package: name@version from package.json ]#################
    typeset -g POWERLEVEL9K_PACKAGE_FOREGROUND=117

    #####################[ node_version: node.js version ]######################
    typeset -g POWERLEVEL9K_NODE_VERSION_FOREGROUND=70
    typeset -g POWERLEVEL9K_NODE_VERSION_PROJECT_ONLY=true

    ################[ kubecontext: current kubernetes context ]#################
    typeset -g POWERLEVEL9K_KUBECONTEXT_SHOW_ON_COMMAND='kubectl|helm|kubens|kubectx|oc|istioctl|kogito|k9s|helmfile|flux|fluxctl|stern|kubeseal|skaffold|kubent|kubecolor|cmctl|sparkctl'
    typeset -g POWERLEVEL9K_KUBECONTEXT_CLASSES=(
        # '*prod*'  PROD    # These values are examples that are unlikely
        # '*test*'  TEST    # to match your needs. Customize them as needed.
        '*'       DEFAULT
    )
    typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_FOREGROUND=26
    typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_CONTENT_EXPANSION=
    POWERLEVEL9K_KUBECONTEXT_DEFAULT_CONTENT_EXPANSION+='${P9K_KUBECONTEXT_CLOUD_CLUSTER:-${P9K_KUBECONTEXT_NAME}}'
    POWERLEVEL9K_KUBECONTEXT_DEFAULT_CONTENT_EXPANSION+='${${:-/$P9K_KUBECONTEXT_NAMESPACE}:#/default}'

    ##############[ gcloud: google cloud cli account and project ]##############
    typeset -g POWERLEVEL9K_GCLOUD_SHOW_ON_COMMAND='gcloud|gcs|gsutil'
    typeset -g POWERLEVEL9K_GCLOUD_FOREGROUND=32
    typeset -g POWERLEVEL9K_GCLOUD_PARTIAL_CONTENT_EXPANSION='${P9K_GCLOUD_PROJECT_ID//\%/%%}'
    typeset -g POWERLEVEL9K_GCLOUD_COMPLETE_CONTENT_EXPANSION='${P9K_GCLOUD_PROJECT_NAME//\%/%%}'
    typeset -g POWERLEVEL9K_GCLOUD_REFRESH_PROJECT_NAME_SECONDS=60

    ###########################[ time: current time ]###########################
    typeset -g POWERLEVEL9K_TIME_FOREGROUND=244
    typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M:%S}'
    typeset -g POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=false

    ##############################[ user defined ]##############################
    typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=off
    typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose
    typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true

    # If p10k is already loaded, reload configuration.
    (( ! $+functions[p10k] )) || p10k reload
}

# Tell `p10k configure` which file it should overwrite.
typeset -g POWERLEVEL9K_CONFIG_FILE=${${(%):-%x}:a}

(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'
